version: '3.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.0.0
    container_name: elasticsearch
    environment:
      - cluster.name=discoverer
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=password
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
      - ./elasticsearch/logs:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.0.0
    container_name: kibana
    volumes:
      - ./kibana/data:/usr/share/kibana/data
      - ./kibana/logs:/usr/share/kibana/logs
    ports:
      - 5601:5601
    networks:
      - elastic

networks:
  elastic: